### ISSUE TITLE
Kernel disables hyper-threading

### ISSUE THREAD

**Issue by mthomos** [PhantomX/chinforpms#1]
Using latest kernel 5.2.7-501 in Dell M3800 with i7-4712HQ , Hyper threading is disabled. Is this the default behavior ?

**Comment by PhantomX** [comment]
Remove old AMD K10 cpu optimization and cores number settings, (default is 4, "--with native" is 8)

Try
```
 sed -e 's|CONFIG_MK10|CONFIG_MHASWELL|' -i kernel-local-cpu
 sed -e '/CONFIG_NR_CPUS/d' -i kernel-local*
```
or to use Fedora defaults
` echo "" > kernel-local-cpu`
